repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.2.1
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
